# Generated by Django 3.2.25 on 2026-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان سند')),
                ('file', models.FileField(upload_to='documents/', verbose_name='فایل سند (docx)')),
                ('full_text', models.TextField(blank=True, null=True, verbose_name='متن کامل استخراج شده')),
                ('is_processed', models.BooleanField(default=False, verbose_name='پردازش و امبد شده در ChromaDB')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بارگذاری')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='QAHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='پرسش')),
                ('answer', models.TextField(verbose_name='پاسخ مدل زبانی')),
                ('eval_score', models.FloatField(blank=True, null=True, verbose_name='نمره ارزیابی Ragas (Faithfulness)')),
                ('is_verified', models.BooleanField(default=True, verbose_name='تایید شده توسط حد آستانه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پرسش')),
            ],
            options={
                'verbose_name': 'تاریخچه پرسش',
                'verbose_name_plural': 'تاریخچه پرسش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
